# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false
jdk:
- jdk8

services:
  - postgresql
  - mysql
before_install:
  #- psql -c 'create database count_words;' -U postgres
  - mysql -e 'CREATE DATABASE count_words;'

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - alexmur008@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
